---

- name: Install rsyslog
  ansible.builtin.package:
    name: "{{ rsyslog_packages }}"
    state: present
  become: yes
  notify: Restart rsyslog

- name: Create configuration from template
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/rsyslog.d/{{ item | basename | regex_replace('\.j2') }}
    mode: "0644"
  become: yes
  loop: "{{ rsyslog_confd }}"
  notify: Restart rsyslog
